---
- name: create ext volume for data
  file: state=directory path={{ ext_postgresql_volume }}

- name: create ext volume for logs
  file: state=directory path={{ ext_postgresql_logs_volume }}

- name: create ext volume for configs
  file: state=directory path={{ ext_postgresql_conf_volume }}/default

- name: put postgresql.conf
  template: src=postgresql.conf dest={{ ext_postgresql_conf_volume }}/default/postgresql.conf

- name: put pg_hba.conf
  template: src=pg_hba.conf dest={{ ext_postgresql_conf_volume }}/default/pg_hba.conf

- name: check if a postgresql container is started
  command: bash -c "docker ps | grep postgresql"
  ignore_errors: True
  register: result

- name: start a postgresql container
  command: docker run -d
            -p={{ postgresql_port }}:5432
            -v {{ ext_postgresql_volume }}:/var/lib/postgresql/9.3
            -v {{ ext_postgresql_logs_volume }}:/var/log/postgresql
            -v {{ ext_postgresql_conf_volume }}:/etc/postgresql/9.3
            --name=postgresql gitinsky/postgresql:0.1.2
  when: result|failed
