---
- name: create ext volume for data
  file: state=directory path={{ ext_postgresql_volume }}

- name: create ext volume for logs
  file: state=directory path={{ ext_postgresql_logs_volume }}

- name: check if a postgresql container is started
  command: bash -c "docker ps | grep postgresql"
  ignore_errors: True
  register: result

- name: start a postgresql container
  command: docker run -d
            -p={{ postgresql_port }}:5432
            -v {{ ext_postgresql_volume }}:/var/lib/postgresql/9.3
            -v {{ ext_postgresql_logs_volume }}:/var/log/postgresql
            --name=postgresql gitinsky/postgresql:0.1.2
  when: result|failed
